// Auto-generated by CodeConverter.
// Run with: dotnet run

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

static class Page {
    static readonly HashSet<string> VOID = new(){
        "area","base","br","col","embed","hr","img","input",
        "link","meta","param","source","track","wbr"
    };

    interface INode { string Render(int indent); }

    static string Pad(int n) => new string(' ', n * 2);

    record Doctype(string Value = "html") : INode {
        public string Render(int i) => Pad(i) + $"<!DOCTYPE {Value}>";
    }
    record Comment(string Text) : INode {
        public string Render(int i) => Pad(i) + $"<!--{Text}-->";
    }
    record TextNode(string Value) : INode {
        public string Render(int i) => Pad(i) + Value;
    }
    record Tag(string Name, Dictionary<string, object> Attrs, List<INode> Children) : INode {
        string AttrStr() => string.Concat(Attrs.Select(kv =>
            kv.Value is bool b && b ? $" {kv.Key}" : $" {kv.Key}=\"{kv.Value}\""));
        public string Render(int i) {
            var p = Pad(i); var a = AttrStr();
            if (VOID.Contains(Name.ToLower())) return $"{p}<{Name}{a}>";
            if (Children.Count == 0) return $"{p}<{Name}{a}></{Name}>";
            if (Children.Count == 1 && Children[0] is TextNode tn && !tn.Value.Contains("\n"))
                return $"{p}<{Name}{a}>{tn.Value}</{Name}>";
            var inner = string.Join("\n", Children.Select(c => c.Render(i + 1)));
            return $"{p}<{Name}{a}>\n{inner}\n{p}</{Name}>";
        }
    }

    static Dictionary<string, object> Attrs(params object[] kv) {
        var m = new Dictionary<string, object>();
        for (int i = 0; i + 1 < kv.Length; i += 2) m[(string)kv[i]] = kv[i + 1];
        return m;
    }

    static string RenderDocument(IEnumerable<INode> nodes) =>
        string.Join("\n", nodes.Select(n => n.Render(0)));

    static List<INode> Document() => new() {
        new Doctype("html"),
        new Tag("html", Attrs("lang", "en"), new List<INode>{
            new Tag("head", Attrs(), new List<INode>{
                new Tag("meta", Attrs("charset", "UTF-8"), new List<INode>()),
                new Tag("title", Attrs(), new List<INode>{
                    new TextNode("Hello")
                })
            }),
            new Tag("body", Attrs(), new List<INode>{
                new Tag("h1", Attrs("class", "title"), new List<INode>{
                    new TextNode("Hello, world!")
                }),
                new Tag("p", Attrs(), new List<INode>{
                    new TextNode("This is a "),
                    new Tag("strong", Attrs(), new List<INode>{
                        new TextNode("test")
                    }),
                    new TextNode(" page.")
                }),
                new Tag("ul", Attrs(), new List<INode>{
                    new Tag("li", Attrs(), new List<INode>{
                        new TextNode("One")
                    }),
                    new Tag("li", Attrs(), new List<INode>{
                        new TextNode("Two")
                    }),
                    new Tag("li", Attrs(), new List<INode>{
                        new TextNode("Three")
                    })
                }),
                new Tag("button", Attrs("onclick", "alert('Hi')", "disabled", true), new List<INode>{
                    new TextNode("Click me")
                })
            })
        })
    };

    static void Main() => Console.WriteLine(RenderDocument(Document()));
}
