"""HTML IR → target-language source.

Each tier-1 language gets a polished, runnable program that reconstructs the
*exact* original HTML using a small Tag/Node DSL idiomatic for that language.
Tier-2 languages fall back to a clean line-by-line string builder.
"""
from textwrap import indent as _indent

VOID = {
    "area", "base", "br", "col", "embed", "hr", "img", "input",
    "link", "meta", "param", "source", "track", "wbr",
}


# =============================================================
#  Shared helpers
# =============================================================
def _esc_dq(s: str) -> str:
    """Escape a string for use inside a double-quoted literal in most languages."""
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t")


def _esc_sq(s: str) -> str:
    return s.replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n")


def _walk_each(children, fn, depth):
    return [fn(c, depth) for c in children]


# =============================================================
#  HTML → Python  (perfected)
# =============================================================
PY_HEADER = '''"""Auto-generated by CodeConverter.

Run with: python3 this_file.py

Reconstructs the original HTML document using a small Tag DSL.
"""

VOID = {
    "area", "base", "br", "col", "embed", "hr", "img", "input",
    "link", "meta", "param", "source", "track", "wbr",
}


class Node:
    def render(self, indent=0):
        raise NotImplementedError


class Doctype(Node):
    def __init__(self, value="html"):
        self.value = value

    def render(self, indent=0):
        return f"{'  ' * indent}<!DOCTYPE {self.value}>"


class Comment(Node):
    def __init__(self, text):
        self.text = text

    def render(self, indent=0):
        return f"{'  ' * indent}<!--{self.text}-->"


class Text(Node):
    def __init__(self, value):
        self.value = value

    def render(self, indent=0):
        return f"{'  ' * indent}{self.value}"


class Tag(Node):
    def __init__(self, name, attrs=None, children=None):
        self.name = name
        self.attrs = attrs or {}
        self.children = children or []

    def _attr_str(self):
        out = []
        for k, v in self.attrs.items():
            if v is True:
                out.append(f" {k}")
            else:
                out.append(f' {k}="{v}"')
        return "".join(out)

    def render(self, indent=0):
        pad = "  " * indent
        attrs = self._attr_str()
        if self.name.lower() in VOID:
            return f"{pad}<{self.name}{attrs}>"
        if not self.children:
            return f"{pad}<{self.name}{attrs}></{self.name}>"
        if (len(self.children) == 1
                and isinstance(self.children[0], Text)
                and "\\n" not in self.children[0].value):
            return f"{pad}<{self.name}{attrs}>{self.children[0].value}</{self.name}>"
        inner = "\\n".join(c.render(indent + 1) for c in self.children)
        return f"{pad}<{self.name}{attrs}>\\n{inner}\\n{pad}</{self.name}>"


def render_document(nodes):
    return "\\n".join(n.render() for n in nodes)
'''


def _py_str(s: str) -> str:
    if "\n" not in s and '"""' not in s:
        return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'
    return '"""' + s.replace("\\", "\\\\").replace('"""', '\\"\\"\\"') + '"""'


def _py_attrs(attrs):
    if not attrs:
        return "{}"
    parts = []
    for k, v in attrs.items():
        if v is True:
            parts.append(f"{_py_str(k)}: True")
        else:
            parts.append(f"{_py_str(k)}: {_py_str(str(v))}")
    return "{" + ", ".join(parts) + "}"


def _py_node(node, depth):
    pad = "    " * depth
    k = node["k"]
    if k == "doctype": return f"{pad}Doctype({_py_str(node['value'])})"
    if k == "hcomment": return f"{pad}Comment({_py_str(node['value'])})"
    if k == "text":     return f"{pad}Text({_py_str(node['value'])})"
    if k == "el":
        attrs = _py_attrs(node["attrs"])
        if not node["children"]:
            args = [_py_str(node["tag"])]
            if node["attrs"]:
                args.append(attrs)
            return f"{pad}Tag({', '.join(args)})"
        inner = ",\n".join(_py_node(c, depth + 1) for c in node["children"])
        attr_arg = ", " + attrs if node["attrs"] else ", {}"
        return f"{pad}Tag({_py_str(node['tag'])}{attr_arg}, [\n{inner}\n{pad}])"
    return f"{pad}Text({_py_str(str(node))})"


def html_to_python(doc):
    body = ",\n".join(_py_node(c, 1) for c in doc["children"])
    return (PY_HEADER + "\n\ndocument = [\n" + body + "\n]\n\n\n"
            'if __name__ == "__main__":\n    print(render_document(document))\n')


# =============================================================
#  HTML → JavaScript  (class-based DOM tree)
# =============================================================
JS_HEADER = '''// Auto-generated by CodeConverter.
// Run with: node this_file.js

const VOID = new Set(["area","base","br","col","embed","hr","img","input",
  "link","meta","param","source","track","wbr"]);

class Doctype {
  constructor(value = "html") { this.value = value; }
  render(indent = 0) { return "  ".repeat(indent) + `<!DOCTYPE ${this.value}>`; }
}

class Comment {
  constructor(text) { this.text = text; }
  render(indent = 0) { return "  ".repeat(indent) + `<!--${this.text}-->`; }
}

class TextNode {
  constructor(value) { this.value = value; }
  render(indent = 0) { return "  ".repeat(indent) + this.value; }
}

class Tag {
  constructor(name, attrs = {}, children = []) {
    this.name = name; this.attrs = attrs; this.children = children;
  }
  _attrStr() {
    return Object.entries(this.attrs).map(([k, v]) =>
      v === true ? ` ${k}` : ` ${k}="${v}"`).join("");
  }
  render(indent = 0) {
    const pad = "  ".repeat(indent);
    const attrs = this._attrStr();
    if (VOID.has(this.name.toLowerCase())) return `${pad}<${this.name}${attrs}>`;
    if (this.children.length === 0) return `${pad}<${this.name}${attrs}></${this.name}>`;
    if (this.children.length === 1 && this.children[0] instanceof TextNode
        && !this.children[0].value.includes("\\n"))
      return `${pad}<${this.name}${attrs}>${this.children[0].value}</${this.name}>`;
    const inner = this.children.map(c => c.render(indent + 1)).join("\\n");
    return `${pad}<${this.name}${attrs}>\\n${inner}\\n${pad}</${this.name}>`;
  }
}

function renderDocument(nodes) {
  return nodes.map(n => n.render()).join("\\n");
}
'''


def _js_str(s: str) -> str:
    return '"' + _esc_dq(s) + '"'


def _js_attrs(attrs):
    if not attrs:
        return "{}"
    parts = []
    for k, v in attrs.items():
        # quote keys that aren't safe identifiers
        key = k if k.replace("-", "").replace(":", "").isidentifier() else _js_str(k)
        if v is True:
            parts.append(f"{key}: true")
        else:
            parts.append(f"{key}: {_js_str(str(v))}")
    return "{" + ", ".join(parts) + "}"


def _js_node(node, depth):
    pad = "  " * depth
    k = node["k"]
    if k == "doctype": return f"{pad}new Doctype({_js_str(node['value'])})"
    if k == "hcomment": return f"{pad}new Comment({_js_str(node['value'])})"
    if k == "text":     return f"{pad}new TextNode({_js_str(node['value'])})"
    if k == "el":
        attrs = _js_attrs(node["attrs"])
        if not node["children"]:
            return f"{pad}new Tag({_js_str(node['tag'])}, {attrs})"
        inner = ",\n".join(_js_node(c, depth + 1) for c in node["children"])
        return (f"{pad}new Tag({_js_str(node['tag'])}, {attrs}, [\n"
                f"{inner}\n{pad}])")
    return f"{pad}new TextNode({_js_str(str(node))})"


def html_to_javascript(doc):
    body = ",\n".join(_js_node(c, 1) for c in doc["children"])
    return (JS_HEADER + "\nconst document_tree = [\n" + body
            + "\n];\n\nconsole.log(renderDocument(document_tree));\n")


# =============================================================
#  HTML → TypeScript  (typed DOM tree)
# =============================================================
TS_HEADER = '''// Auto-generated by CodeConverter.
// Run with: ts-node this_file.ts  (or compile + node)

const VOID = new Set<string>(["area","base","br","col","embed","hr","img","input",
  "link","meta","param","source","track","wbr"]);

interface Node {
  render(indent?: number): string;
}

class Doctype implements Node {
  constructor(public value: string = "html") {}
  render(indent = 0): string { return "  ".repeat(indent) + `<!DOCTYPE ${this.value}>`; }
}

class Comment implements Node {
  constructor(public text: string) {}
  render(indent = 0): string { return "  ".repeat(indent) + `<!--${this.text}-->`; }
}

class TextNode implements Node {
  constructor(public value: string) {}
  render(indent = 0): string { return "  ".repeat(indent) + this.value; }
}

type AttrValue = string | true;

class Tag implements Node {
  constructor(
    public name: string,
    public attrs: Record<string, AttrValue> = {},
    public children: Node[] = []
  ) {}
  private _attrStr(): string {
    return Object.entries(this.attrs).map(([k, v]) =>
      v === true ? ` ${k}` : ` ${k}="${v}"`).join("");
  }
  render(indent = 0): string {
    const pad = "  ".repeat(indent);
    const attrs = this._attrStr();
    if (VOID.has(this.name.toLowerCase())) return `${pad}<${this.name}${attrs}>`;
    if (this.children.length === 0) return `${pad}<${this.name}${attrs}></${this.name}>`;
    if (this.children.length === 1 && this.children[0] instanceof TextNode
        && !(this.children[0] as TextNode).value.includes("\\n"))
      return `${pad}<${this.name}${attrs}>${(this.children[0] as TextNode).value}</${this.name}>`;
    const inner = this.children.map(c => c.render(indent + 1)).join("\\n");
    return `${pad}<${this.name}${attrs}>\\n${inner}\\n${pad}</${this.name}>`;
  }
}

function renderDocument(nodes: Node[]): string {
  return nodes.map(n => n.render()).join("\\n");
}
'''


def html_to_typescript(doc):
    body = ",\n".join(_js_node(c, 1) for c in doc["children"])
    return (TS_HEADER + "\nconst documentTree: Node[] = [\n" + body
            + "\n];\n\nconsole.log(renderDocument(documentTree));\n")


# =============================================================
#  HTML → Java
# =============================================================
JAVA_HEADER = '''// Auto-generated by CodeConverter.
// Compile + run:  javac Page.java && java Page

import java.util.*;

public class Page {
    static final Set<String> VOID = Set.of(
        "area","base","br","col","embed","hr","img","input",
        "link","meta","param","source","track","wbr"
    );

    interface Node { String render(int indent); }

    static String pad(int n) { return "  ".repeat(n); }

    static class Doctype implements Node {
        final String value;
        Doctype(String v) { this.value = v; }
        public String render(int i) { return pad(i) + "<!DOCTYPE " + value + ">"; }
    }

    static class Comment implements Node {
        final String text;
        Comment(String t) { this.text = t; }
        public String render(int i) { return pad(i) + "<!--" + text + "-->"; }
    }

    static class TextNode implements Node {
        final String value;
        TextNode(String v) { this.value = v; }
        public String render(int i) { return pad(i) + value; }
    }

    static class Tag implements Node {
        final String name;
        final LinkedHashMap<String, Object> attrs;
        final List<Node> children;
        Tag(String name, LinkedHashMap<String, Object> attrs, List<Node> children) {
            this.name = name; this.attrs = attrs; this.children = children;
        }
        String attrStr() {
            StringBuilder sb = new StringBuilder();
            for (var e : attrs.entrySet()) {
                if (Boolean.TRUE.equals(e.getValue())) sb.append(" ").append(e.getKey());
                else sb.append(" ").append(e.getKey()).append("=\\"").append(e.getValue()).append("\\"");
            }
            return sb.toString();
        }
        public String render(int i) {
            String p = pad(i), a = attrStr();
            if (VOID.contains(name.toLowerCase())) return p + "<" + name + a + ">";
            if (children.isEmpty()) return p + "<" + name + a + "></" + name + ">";
            if (children.size() == 1 && children.get(0) instanceof TextNode tn
                    && !tn.value.contains("\\n"))
                return p + "<" + name + a + ">" + tn.value + "</" + name + ">";
            StringBuilder sb = new StringBuilder();
            sb.append(p).append("<").append(name).append(a).append(">\\n");
            for (int k = 0; k < children.size(); k++) {
                sb.append(children.get(k).render(i + 1));
                if (k < children.size() - 1) sb.append("\\n");
            }
            sb.append("\\n").append(p).append("</").append(name).append(">");
            return sb.toString();
        }
    }

    @SuppressWarnings("unchecked")
    static LinkedHashMap<String, Object> attrs(Object... kv) {
        var m = new LinkedHashMap<String, Object>();
        for (int i = 0; i + 1 < kv.length; i += 2) m.put((String) kv[i], kv[i + 1]);
        return m;
    }

    static String renderDocument(List<Node> nodes) {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < nodes.size(); i++) {
            sb.append(nodes.get(i).render(0));
            if (i < nodes.size() - 1) sb.append("\\n");
        }
        return sb.toString();
    }

    public static void main(String[] args) {
        System.out.println(renderDocument(document()));
    }

    static List<Node> document() {
        return List.of(
'''


def _java_str(s):
    return '"' + _esc_dq(s) + '"'


def _java_attrs(attrs):
    if not attrs:
        return "attrs()"
    parts = []
    for k, v in attrs.items():
        parts.append(_java_str(k))
        parts.append("true" if v is True else _java_str(str(v)))
    return "attrs(" + ", ".join(parts) + ")"


def _java_node(node, depth):
    pad = "    " * depth
    k = node["k"]
    if k == "doctype": return f"{pad}new Doctype({_java_str(node['value'])})"
    if k == "hcomment": return f"{pad}new Comment({_java_str(node['value'])})"
    if k == "text":     return f"{pad}new TextNode({_java_str(node['value'])})"
    if k == "el":
        a = _java_attrs(node["attrs"])
        if not node["children"]:
            return f"{pad}new Tag({_java_str(node['tag'])}, {a}, List.of())"
        inner = ",\n".join(_java_node(c, depth + 1) for c in node["children"])
        return (f"{pad}new Tag({_java_str(node['tag'])}, {a}, List.of(\n"
                f"{inner}\n{pad}))")
    return f"{pad}new TextNode({_java_str(str(node))})"


def html_to_java(doc):
    body = ",\n".join(_java_node(c, 3) for c in doc["children"])
    return (JAVA_HEADER + body + "\n        );\n    }\n}\n")


# =============================================================
#  HTML → C#
# =============================================================
CS_HEADER = '''// Auto-generated by CodeConverter.
// Run with: dotnet run

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

static class Page {
    static readonly HashSet<string> VOID = new(){
        "area","base","br","col","embed","hr","img","input",
        "link","meta","param","source","track","wbr"
    };

    interface INode { string Render(int indent); }

    static string Pad(int n) => new string(' ', n * 2);

    record Doctype(string Value = "html") : INode {
        public string Render(int i) => Pad(i) + $"<!DOCTYPE {Value}>";
    }
    record Comment(string Text) : INode {
        public string Render(int i) => Pad(i) + $"<!--{Text}-->";
    }
    record TextNode(string Value) : INode {
        public string Render(int i) => Pad(i) + Value;
    }
    record Tag(string Name, Dictionary<string, object> Attrs, List<INode> Children) : INode {
        string AttrStr() => string.Concat(Attrs.Select(kv =>
            kv.Value is bool b && b ? $" {kv.Key}" : $" {kv.Key}=\\"{kv.Value}\\""));
        public string Render(int i) {
            var p = Pad(i); var a = AttrStr();
            if (VOID.Contains(Name.ToLower())) return $"{p}<{Name}{a}>";
            if (Children.Count == 0) return $"{p}<{Name}{a}></{Name}>";
            if (Children.Count == 1 && Children[0] is TextNode tn && !tn.Value.Contains("\\n"))
                return $"{p}<{Name}{a}>{tn.Value}</{Name}>";
            var inner = string.Join("\\n", Children.Select(c => c.Render(i + 1)));
            return $"{p}<{Name}{a}>\\n{inner}\\n{p}</{Name}>";
        }
    }

    static Dictionary<string, object> Attrs(params object[] kv) {
        var m = new Dictionary<string, object>();
        for (int i = 0; i + 1 < kv.Length; i += 2) m[(string)kv[i]] = kv[i + 1];
        return m;
    }

    static string RenderDocument(IEnumerable<INode> nodes) =>
        string.Join("\\n", nodes.Select(n => n.Render(0)));

    static List<INode> Document() => new() {
'''


def _cs_str(s): return '"' + _esc_dq(s) + '"'


def _cs_attrs(attrs):
    if not attrs:
        return "Attrs()"
    parts = []
    for k, v in attrs.items():
        parts.append(_cs_str(k))
        parts.append("true" if v is True else _cs_str(str(v)))
    return "Attrs(" + ", ".join(parts) + ")"


def _cs_node(node, depth):
    pad = "        " + "    " * depth
    k = node["k"]
    if k == "doctype": return f"{pad}new Doctype({_cs_str(node['value'])})"
    if k == "hcomment": return f"{pad}new Comment({_cs_str(node['value'])})"
    if k == "text":     return f"{pad}new TextNode({_cs_str(node['value'])})"
    if k == "el":
        a = _cs_attrs(node["attrs"])
        if not node["children"]:
            return f"{pad}new Tag({_cs_str(node['tag'])}, {a}, new List<INode>())"
        inner = ",\n".join(_cs_node(c, depth + 1) for c in node["children"])
        return (f"{pad}new Tag({_cs_str(node['tag'])}, {a}, new List<INode>{{\n"
                f"{inner}\n{pad}}})")
    return f"{pad}new TextNode({_cs_str(str(node))})"


def html_to_csharp(doc):
    body = ",\n".join(_cs_node(c, 0) for c in doc["children"])
    return (CS_HEADER + body + "\n    };\n\n"
            "    static void Main() => Console.WriteLine(RenderDocument(Document()));\n}\n")


# =============================================================
#  HTML → C++
# =============================================================
CPP_HEADER = '''// Auto-generated by CodeConverter.
// Compile + run:  c++ -std=c++17 page.cpp -o page && ./page

#include <iostream>
#include <string>
#include <vector>
#include <utility>
#include <memory>
#include <set>

const std::set<std::string> VOID{"area","base","br","col","embed","hr","img","input",
    "link","meta","param","source","track","wbr"};

struct Node {
    virtual std::string render(int indent = 0) const = 0;
    virtual ~Node() = default;
};
using NodePtr = std::shared_ptr<Node>;

static std::string pad(int n) { return std::string(n * 2, ' '); }

struct Doctype : Node {
    std::string value;
    Doctype(std::string v) : value(std::move(v)) {}
    std::string render(int i) const override { return pad(i) + "<!DOCTYPE " + value + ">"; }
};

struct Comment : Node {
    std::string text;
    Comment(std::string t) : text(std::move(t)) {}
    std::string render(int i) const override { return pad(i) + "<!--" + text + "-->"; }
};

struct TextNode : Node {
    std::string value;
    TextNode(std::string v) : value(std::move(v)) {}
    std::string render(int i) const override { return pad(i) + value; }
};

struct Attr { std::string key; std::string value; bool boolean = false; };

struct Tag : Node {
    std::string name;
    std::vector<Attr> attrs;
    std::vector<NodePtr> children;
    Tag(std::string n, std::vector<Attr> a, std::vector<NodePtr> c)
        : name(std::move(n)), attrs(std::move(a)), children(std::move(c)) {}
    std::string attrStr() const {
        std::string s;
        for (const auto& a : attrs) {
            if (a.boolean) s += " " + a.key;
            else s += " " + a.key + "=\\"" + a.value + "\\"";
        }
        return s;
    }
    std::string render(int i) const override {
        std::string p = pad(i), a = attrStr();
        std::string lower = name; for (auto& c : lower) c = (char)tolower(c);
        if (VOID.count(lower)) return p + "<" + name + a + ">";
        if (children.empty()) return p + "<" + name + a + "></" + name + ">";
        if (children.size() == 1) {
            if (auto tn = dynamic_cast<TextNode*>(children[0].get())) {
                if (tn->value.find('\\n') == std::string::npos)
                    return p + "<" + name + a + ">" + tn->value + "</" + name + ">";
            }
        }
        std::string inner;
        for (size_t k = 0; k < children.size(); ++k) {
            inner += children[k]->render(i + 1);
            if (k + 1 < children.size()) inner += "\\n";
        }
        return p + "<" + name + a + ">\\n" + inner + "\\n" + p + "</" + name + ">";
    }
};

static std::string renderDocument(const std::vector<NodePtr>& nodes) {
    std::string out;
    for (size_t i = 0; i < nodes.size(); ++i) {
        out += nodes[i]->render(0);
        if (i + 1 < nodes.size()) out += "\\n";
    }
    return out;
}

template<typename T, typename... Args>
NodePtr make(Args&&... args) { return std::make_shared<T>(std::forward<Args>(args)...); }

int main() {
    std::vector<NodePtr> document = {
'''


def _cpp_str(s): return '"' + _esc_dq(s) + '"'


def _cpp_attrs(attrs):
    if not attrs:
        return "std::vector<Attr>{}"
    parts = []
    for k, v in attrs.items():
        if v is True:
            parts.append('Attr{"' + _esc_dq(k) + '", "", true}')
        else:
            parts.append('Attr{"' + _esc_dq(k) + '", "' + _esc_dq(str(v)) + '"}')
    return "std::vector<Attr>{" + ", ".join(parts) + "}"


def _cpp_node(node, depth):
    pad = "        " + "    " * depth
    k = node["k"]
    if k == "doctype": return f"{pad}make<Doctype>({_cpp_str(node['value'])})"
    if k == "hcomment": return f"{pad}make<Comment>({_cpp_str(node['value'])})"
    if k == "text":     return f"{pad}make<TextNode>({_cpp_str(node['value'])})"
    if k == "el":
        a = _cpp_attrs(node["attrs"])
        if not node["children"]:
            return f"{pad}make<Tag>({_cpp_str(node['tag'])}, {a}, std::vector<NodePtr>{{}})"
        inner = ",\n".join(_cpp_node(c, depth + 1) for c in node["children"])
        return (f"{pad}make<Tag>({_cpp_str(node['tag'])}, {a}, std::vector<NodePtr>{{\n"
                f"{inner}\n{pad}}})")
    return f"{pad}make<TextNode>({_cpp_str(str(node))})"


def html_to_cpp(doc):
    body = ",\n".join(_cpp_node(c, 0) for c in doc["children"])
    return (CPP_HEADER + body + "\n    };\n\n"
            "    std::cout << renderDocument(document) << std::endl;\n"
            "    return 0;\n}\n")


# =============================================================
#  HTML → Swift
# =============================================================
SWIFT_HEADER = '''// Auto-generated by CodeConverter.
// Run:  swift this_file.swift

import Foundation

let VOID: Set<String> = ["area","base","br","col","embed","hr","img","input",
    "link","meta","param","source","track","wbr"]

protocol Node { func render(_ indent: Int) -> String }

func pad(_ n: Int) -> String { String(repeating: "  ", count: n) }

struct Doctype: Node {
    let value: String
    func render(_ i: Int) -> String { "\\(pad(i))<!DOCTYPE \\(value)>" }
}

struct Comment: Node {
    let text: String
    func render(_ i: Int) -> String { "\\(pad(i))<!--\\(text)-->" }
}

struct TextNode: Node {
    let value: String
    func render(_ i: Int) -> String { "\\(pad(i))\\(value)" }
}

enum AttrValue { case str(String), bool(Bool) }

struct Tag: Node {
    let name: String
    let attrs: [(String, AttrValue)]
    let children: [Node]
    func attrStr() -> String {
        attrs.map { (k, v) -> String in
            switch v {
            case .bool(true): return " \\(k)"
            case .bool(false): return ""
            case .str(let s): return " \\(k)=\\"\\(s)\\""
            }
        }.joined()
    }
    func render(_ i: Int) -> String {
        let p = pad(i), a = attrStr()
        if VOID.contains(name.lowercased()) { return "\\(p)<\\(name)\\(a)>" }
        if children.isEmpty { return "\\(p)<\\(name)\\(a)></\\(name)>" }
        if children.count == 1, let tn = children[0] as? TextNode, !tn.value.contains("\\n") {
            return "\\(p)<\\(name)\\(a)>\\(tn.value)</\\(name)>"
        }
        let inner = children.map { $0.render(i + 1) }.joined(separator: "\\n")
        return "\\(p)<\\(name)\\(a)>\\n\\(inner)\\n\\(p)</\\(name)>"
    }
}

func renderDocument(_ nodes: [Node]) -> String {
    nodes.map { $0.render(0) }.joined(separator: "\\n")
}
'''


def _swift_str(s): return '"' + _esc_dq(s) + '"'


def _swift_attrs(attrs):
    if not attrs:
        return "[]"
    parts = []
    for k, v in attrs.items():
        if v is True:
            parts.append(f"({_swift_str(k)}, .bool(true))")
        else:
            parts.append(f"({_swift_str(k)}, .str({_swift_str(str(v))}))")
    return "[" + ", ".join(parts) + "]"


def _swift_node(node, depth):
    pad = "    " * depth
    k = node["k"]
    if k == "doctype": return f"{pad}Doctype(value: {_swift_str(node['value'])})"
    if k == "hcomment": return f"{pad}Comment(text: {_swift_str(node['value'])})"
    if k == "text":     return f"{pad}TextNode(value: {_swift_str(node['value'])})"
    if k == "el":
        a = _swift_attrs(node["attrs"])
        if not node["children"]:
            return f"{pad}Tag(name: {_swift_str(node['tag'])}, attrs: {a}, children: [])"
        inner = ",\n".join(_swift_node(c, depth + 1) for c in node["children"])
        return (f"{pad}Tag(name: {_swift_str(node['tag'])}, attrs: {a}, children: [\n"
                f"{inner}\n{pad}])")
    return f"{pad}TextNode(value: {_swift_str(str(node))})"


def html_to_swift(doc):
    body = ",\n".join(_swift_node(c, 1) for c in doc["children"])
    return (SWIFT_HEADER + "\nlet document: [Node] = [\n" + body
            + "\n]\n\nprint(renderDocument(document))\n")


# =============================================================
#  HTML → Go
# =============================================================
GO_HEADER = '''// Auto-generated by CodeConverter.
// Run:  go run this_file.go

package main

import (
\t"fmt"
\t"strings"
)

var VOID = map[string]bool{
\t"area": true, "base": true, "br": true, "col": true, "embed": true,
\t"hr": true, "img": true, "input": true, "link": true, "meta": true,
\t"param": true, "source": true, "track": true, "wbr": true,
}

type Node interface{ Render(indent int) string }

func pad(n int) string { return strings.Repeat("  ", n) }

type Doctype struct{ Value string }
func (d Doctype) Render(i int) string { return pad(i) + "<!DOCTYPE " + d.Value + ">" }

type Comment struct{ Text string }
func (c Comment) Render(i int) string { return pad(i) + "<!--" + c.Text + "-->" }

type TextNode struct{ Value string }
func (t TextNode) Render(i int) string { return pad(i) + t.Value }

type Attr struct {
\tKey, Value string
\tBool       bool
}

type Tag struct {
\tName     string
\tAttrs    []Attr
\tChildren []Node
}

func (t Tag) attrStr() string {
\tvar b strings.Builder
\tfor _, a := range t.Attrs {
\t\tif a.Bool {
\t\t\tb.WriteString(" " + a.Key)
\t\t} else {
\t\t\tb.WriteString(" " + a.Key + "=\\"" + a.Value + "\\"")
\t\t}
\t}
\treturn b.String()
}

func (t Tag) Render(i int) string {
\tp, a := pad(i), t.attrStr()
\tif VOID[strings.ToLower(t.Name)] {
\t\treturn p + "<" + t.Name + a + ">"
\t}
\tif len(t.Children) == 0 {
\t\treturn p + "<" + t.Name + a + "></" + t.Name + ">"
\t}
\tif len(t.Children) == 1 {
\t\tif tn, ok := t.Children[0].(TextNode); ok && !strings.Contains(tn.Value, "\\n") {
\t\t\treturn p + "<" + t.Name + a + ">" + tn.Value + "</" + t.Name + ">"
\t\t}
\t}
\tparts := make([]string, len(t.Children))
\tfor k, c := range t.Children {
\t\tparts[k] = c.Render(i + 1)
\t}
\treturn p + "<" + t.Name + a + ">\\n" + strings.Join(parts, "\\n") + "\\n" + p + "</" + t.Name + ">"
}

func renderDocument(nodes []Node) string {
\tparts := make([]string, len(nodes))
\tfor i, n := range nodes {
\t\tparts[i] = n.Render(0)
\t}
\treturn strings.Join(parts, "\\n")
}

func main() {
\tdocument := []Node{
'''


def _go_str(s): return '"' + _esc_dq(s) + '"'


def _go_attrs(attrs):
    if not attrs:
        return "nil"
    parts = []
    for k, v in attrs.items():
        if v is True:
            parts.append('{Key: "' + _esc_dq(k) + '", Bool: true}')
        else:
            parts.append('{Key: "' + _esc_dq(k) + '", Value: "' + _esc_dq(str(v)) + '"}')
    return "[]Attr{" + ", ".join(parts) + "}"


def _go_node(node, depth):
    pad = "\t" * depth
    k = node["k"]
    if k == "doctype": return f"{pad}Doctype{{Value: {_go_str(node['value'])}}}"
    if k == "hcomment": return f"{pad}Comment{{Text: {_go_str(node['value'])}}}"
    if k == "text":     return f"{pad}TextNode{{Value: {_go_str(node['value'])}}}"
    if k == "el":
        a = _go_attrs(node["attrs"])
        if not node["children"]:
            return f"{pad}Tag{{Name: {_go_str(node['tag'])}, Attrs: {a}}}"
        inner = ",\n".join(_go_node(c, depth + 1) for c in node["children"])
        return (f"{pad}Tag{{Name: {_go_str(node['tag'])}, Attrs: {a}, Children: []Node{{\n"
                f"{inner},\n{pad}}}}}")
    return f"{pad}TextNode{{Value: {_go_str(str(node))}}}"


def html_to_go(doc):
    body = ",\n".join(_go_node(c, 2) for c in doc["children"])
    return (GO_HEADER + body + ",\n\t}\n\tfmt.Println(renderDocument(document))\n}\n")


# =============================================================
#  HTML → Rust
# =============================================================
RUST_HEADER = '''// Auto-generated by CodeConverter.
// Run:  rustc this_file.rs && ./this_file

use std::collections::HashSet;

fn pad(n: usize) -> String { "  ".repeat(n) }

#[derive(Debug)]
enum AttrValue { Str(String), Bool }

#[derive(Debug)]
struct Attr { key: String, value: AttrValue }

#[derive(Debug)]
enum Node {
    Doctype(String),
    Comment(String),
    Text(String),
    Tag { name: String, attrs: Vec<Attr>, children: Vec<Node> },
}

impl Node {
    fn render(&self, indent: usize) -> String {
        let voids: HashSet<&str> = ["area","base","br","col","embed","hr","img","input",
            "link","meta","param","source","track","wbr"].iter().copied().collect();
        match self {
            Node::Doctype(v) => format!("{}<!DOCTYPE {}>", pad(indent), v),
            Node::Comment(t) => format!("{}<!--{}-->", pad(indent), t),
            Node::Text(v)    => format!("{}{}", pad(indent), v),
            Node::Tag { name, attrs, children } => {
                let p = pad(indent);
                let a: String = attrs.iter().map(|a| match &a.value {
                    AttrValue::Bool   => format!(" {}", a.key),
                    AttrValue::Str(s) => format!(" {}=\\"{}\\"", a.key, s),
                }).collect();
                if voids.contains(name.to_lowercase().as_str()) {
                    return format!("{}<{}{}>", p, name, a);
                }
                if children.is_empty() {
                    return format!("{}<{}{}></{}>", p, name, a, name);
                }
                if children.len() == 1 {
                    if let Node::Text(v) = &children[0] {
                        if !v.contains('\\n') {
                            return format!("{}<{}{}>{}</{}>", p, name, a, v, name);
                        }
                    }
                }
                let inner: Vec<String> = children.iter().map(|c| c.render(indent + 1)).collect();
                format!("{}<{}{}>\\n{}\\n{}</{}>", p, name, a, inner.join("\\n"), p, name)
            }
        }
    }
}

fn render_document(nodes: &[Node]) -> String {
    nodes.iter().map(|n| n.render(0)).collect::<Vec<_>>().join("\\n")
}

fn main() {
    let document = vec![
'''


def _rust_str(s): return '"' + _esc_dq(s) + '".to_string()'


def _rust_attrs(attrs):
    if not attrs:
        return "vec![]"
    parts = []
    for k, v in attrs.items():
        if v is True:
            parts.append(f"Attr {{ key: {_rust_str(k)}, value: AttrValue::Bool }}")
        else:
            parts.append(f"Attr {{ key: {_rust_str(k)}, value: AttrValue::Str({_rust_str(str(v))}) }}")
    return "vec![" + ", ".join(parts) + "]"


def _rust_node(node, depth):
    pad = "    " * depth
    k = node["k"]
    if k == "doctype": return f"{pad}Node::Doctype({_rust_str(node['value'])})"
    if k == "hcomment": return f"{pad}Node::Comment({_rust_str(node['value'])})"
    if k == "text":     return f"{pad}Node::Text({_rust_str(node['value'])})"
    if k == "el":
        a = _rust_attrs(node["attrs"])
        if not node["children"]:
            return (f"{pad}Node::Tag {{ name: {_rust_str(node['tag'])}, attrs: {a}, children: vec![] }}")
        inner = ",\n".join(_rust_node(c, depth + 1) for c in node["children"])
        return (f"{pad}Node::Tag {{ name: {_rust_str(node['tag'])}, attrs: {a}, children: vec![\n"
                f"{inner}\n{pad}] }}")
    return f"{pad}Node::Text({_rust_str(str(node))})"


def html_to_rust(doc):
    body = ",\n".join(_rust_node(c, 2) for c in doc["children"])
    return (RUST_HEADER + body + "\n    ];\n    println!(\"{}\", render_document(&document));\n}\n")


# =============================================================
#  HTML → Kotlin
# =============================================================
KOTLIN_HEADER = '''// Auto-generated by CodeConverter.
// Run:  kotlinc -script this_file.kts   (or build a .kt with main)

val VOID = setOf("area","base","br","col","embed","hr","img","input",
    "link","meta","param","source","track","wbr")

sealed interface Node { fun render(indent: Int = 0): String }

fun pad(n: Int) = "  ".repeat(n)

data class Doctype(val value: String = "html") : Node {
    override fun render(indent: Int) = "${pad(indent)}<!DOCTYPE $value>"
}
data class Comment(val text: String) : Node {
    override fun render(indent: Int) = "${pad(indent)}<!--$text-->"
}
data class TextNode(val value: String) : Node {
    override fun render(indent: Int) = "${pad(indent)}$value"
}
sealed class AttrValue { data class Str(val v: String) : AttrValue(); object Bool : AttrValue() }
data class Tag(val name: String, val attrs: List<Pair<String, AttrValue>> = emptyList(),
               val children: List<Node> = emptyList()) : Node {
    private fun attrStr() = attrs.joinToString("") { (k, v) ->
        when (v) { is AttrValue.Bool -> " $k"; is AttrValue.Str -> " $k=\\"${v.v}\\"" }
    }
    override fun render(indent: Int): String {
        val p = pad(indent); val a = attrStr()
        if (name.lowercase() in VOID) return "$p<$name$a>"
        if (children.isEmpty()) return "$p<$name$a></$name>"
        val first = children.firstOrNull()
        if (children.size == 1 && first is TextNode && '\\n' !in first.value)
            return "$p<$name$a>${first.value}</$name>"
        val inner = children.joinToString("\\n") { it.render(indent + 1) }
        return "$p<$name$a>\\n$inner\\n$p</$name>"
    }
}

fun renderDocument(nodes: List<Node>) = nodes.joinToString("\\n") { it.render(0) }

fun main() {
    val document: List<Node> = listOf(
'''


def _kt_str(s): return '"' + _esc_dq(s) + '"'


def _kt_attrs(attrs):
    if not attrs:
        return "emptyList()"
    parts = []
    for k, v in attrs.items():
        if v is True:
            parts.append(f"{_kt_str(k)} to AttrValue.Bool")
        else:
            parts.append(f"{_kt_str(k)} to AttrValue.Str({_kt_str(str(v))})")
    return "listOf(" + ", ".join(parts) + ")"


def _kt_node(node, depth):
    pad = "    " * depth
    k = node["k"]
    if k == "doctype": return f"{pad}Doctype({_kt_str(node['value'])})"
    if k == "hcomment": return f"{pad}Comment({_kt_str(node['value'])})"
    if k == "text":     return f"{pad}TextNode({_kt_str(node['value'])})"
    if k == "el":
        a = _kt_attrs(node["attrs"])
        if not node["children"]:
            return f"{pad}Tag({_kt_str(node['tag'])}, {a})"
        inner = ",\n".join(_kt_node(c, depth + 1) for c in node["children"])
        return (f"{pad}Tag({_kt_str(node['tag'])}, {a}, listOf(\n"
                f"{inner}\n{pad}))")
    return f"{pad}TextNode({_kt_str(str(node))})"


def html_to_kotlin(doc):
    body = ",\n".join(_kt_node(c, 2) for c in doc["children"])
    return (KOTLIN_HEADER + body + "\n    )\n    println(renderDocument(document))\n}\n")


# =============================================================
#  HTML → PHP
# =============================================================
PHP_HEADER = '''<?php
// Auto-generated by CodeConverter.
// Run:  php this_file.php

const VOID = ["area","base","br","col","embed","hr","img","input",
    "link","meta","param","source","track","wbr"];

interface Node { public function render(int $indent = 0): string; }

function pad(int $n): string { return str_repeat("  ", $n); }

class Doctype implements Node {
    public function __construct(public string $value = "html") {}
    public function render(int $i = 0): string { return pad($i) . "<!DOCTYPE {$this->value}>"; }
}
class Comment implements Node {
    public function __construct(public string $text) {}
    public function render(int $i = 0): string { return pad($i) . "<!--{$this->text}-->"; }
}
class TextNode implements Node {
    public function __construct(public string $value) {}
    public function render(int $i = 0): string { return pad($i) . $this->value; }
}
class Tag implements Node {
    public function __construct(
        public string $name,
        public array $attrs = [],
        public array $children = []
    ) {}
    private function attrStr(): string {
        $out = "";
        foreach ($this->attrs as $k => $v) {
            $out .= ($v === true) ? " $k" : " $k=\\"$v\\"";
        }
        return $out;
    }
    public function render(int $i = 0): string {
        $p = pad($i); $a = $this->attrStr();
        if (in_array(strtolower($this->name), VOID)) return "$p<{$this->name}$a>";
        if (count($this->children) === 0) return "$p<{$this->name}$a></{$this->name}>";
        if (count($this->children) === 1 && $this->children[0] instanceof TextNode
            && strpos($this->children[0]->value, "\\n") === false)
            return "$p<{$this->name}$a>{$this->children[0]->value}</{$this->name}>";
        $inner = implode("\\n", array_map(fn($c) => $c->render($i + 1), $this->children));
        return "$p<{$this->name}$a>\\n$inner\\n$p</{$this->name}>";
    }
}

function renderDocument(array $nodes): string {
    return implode("\\n", array_map(fn($n) => $n->render(0), $nodes));
}
'''


def _php_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$").replace("\n", "\\n") + '"'


def _php_attrs(attrs):
    if not attrs:
        return "[]"
    parts = []
    for k, v in attrs.items():
        if v is True:
            parts.append(f"{_php_str(k)} => true")
        else:
            parts.append(f"{_php_str(k)} => {_php_str(str(v))}")
    return "[" + ", ".join(parts) + "]"


def _php_node(node, depth):
    pad = "    " * depth
    k = node["k"]
    if k == "doctype": return f"{pad}new Doctype({_php_str(node['value'])})"
    if k == "hcomment": return f"{pad}new Comment({_php_str(node['value'])})"
    if k == "text":     return f"{pad}new TextNode({_php_str(node['value'])})"
    if k == "el":
        a = _php_attrs(node["attrs"])
        if not node["children"]:
            return f"{pad}new Tag({_php_str(node['tag'])}, {a})"
        inner = ",\n".join(_php_node(c, depth + 1) for c in node["children"])
        return (f"{pad}new Tag({_php_str(node['tag'])}, {a}, [\n"
                f"{inner}\n{pad}])")
    return f"{pad}new TextNode({_php_str(str(node))})"


def html_to_php(doc):
    body = ",\n".join(_php_node(c, 1) for c in doc["children"])
    return (PHP_HEADER + "\n$document = [\n" + body
            + "\n];\n\necho renderDocument($document) . \"\\n\";\n")


# =============================================================
#  HTML → Ruby
# =============================================================
RUBY_HEADER = '''# Auto-generated by CodeConverter.
# Run:  ruby this_file.rb

require "set"
VOID = %w[area base br col embed hr img input link meta param source track wbr].to_set

def pad(n); "  " * n; end

class Doctype
  def initialize(value = "html"); @value = value; end
  def render(indent = 0); "#{pad(indent)}<!DOCTYPE #{@value}>"; end
end

class Comment
  def initialize(text); @text = text; end
  def render(indent = 0); "#{pad(indent)}<!--#{@text}-->"; end
end

class TextNode
  attr_reader :value
  def initialize(value); @value = value; end
  def render(indent = 0); "#{pad(indent)}#{@value}"; end
end

class Tag
  def initialize(name, attrs = {}, children = [])
    @name, @attrs, @children = name, attrs, children
  end
  def attr_str
    @attrs.map { |k, v| v == true ? " #{k}" : " #{k}=\\"#{v}\\"" }.join
  end
  def render(indent = 0)
    p = pad(indent); a = attr_str
    return "#{p}<#{@name}#{a}>" if VOID.include?(@name.downcase)
    return "#{p}<#{@name}#{a}></#{@name}>" if @children.empty?
    if @children.size == 1 && @children[0].is_a?(TextNode) && !@children[0].value.include?("\\n")
      return "#{p}<#{@name}#{a}>#{@children[0].value}</#{@name}>"
    end
    inner = @children.map { |c| c.render(indent + 1) }.join("\\n")
    "#{p}<#{@name}#{a}>\\n#{inner}\\n#{p}</#{@name}>"
  end
end

def render_document(nodes); nodes.map { |n| n.render(0) }.join("\\n"); end
'''


def _ruby_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("#{", "\\#{").replace("\n", "\\n") + '"'


def _ruby_attrs(attrs):
    if not attrs:
        return "{}"
    parts = []
    for k, v in attrs.items():
        if v is True:
            parts.append(f"{_ruby_str(k)} => true")
        else:
            parts.append(f"{_ruby_str(k)} => {_ruby_str(str(v))}")
    return "{" + ", ".join(parts) + "}"


def _ruby_node(node, depth):
    pad = "  " * depth
    k = node["k"]
    if k == "doctype": return f"{pad}Doctype.new({_ruby_str(node['value'])})"
    if k == "hcomment": return f"{pad}Comment.new({_ruby_str(node['value'])})"
    if k == "text":     return f"{pad}TextNode.new({_ruby_str(node['value'])})"
    if k == "el":
        a = _ruby_attrs(node["attrs"])
        if not node["children"]:
            return f"{pad}Tag.new({_ruby_str(node['tag'])}, {a})"
        inner = ",\n".join(_ruby_node(c, depth + 1) for c in node["children"])
        return (f"{pad}Tag.new({_ruby_str(node['tag'])}, {a}, [\n"
                f"{inner}\n{pad}])")
    return f"{pad}TextNode.new({_ruby_str(str(node))})"


def html_to_ruby(doc):
    body = ",\n".join(_ruby_node(c, 1) for c in doc["children"])
    return (RUBY_HEADER + "\ndocument = [\n" + body
            + "\n]\n\nputs render_document(document)\n")


# =============================================================
#  HTML round-trip + tier-2 line-builder fallback
# =============================================================
def _flatten_to_lines(nodes, depth=0):
    out = []
    for n in nodes:
        line = _render_html_node(n, depth)
        if line is not None:
            out.append(line)
    return out


def _render_html_node(n, depth):
    pad = "  " * depth
    if n["k"] == "doctype":
        return f"{pad}<!DOCTYPE {n['value']}>"
    if n["k"] == "hcomment":
        return f"{pad}<!--{n['value']}-->"
    if n["k"] == "text":
        v = n["value"].rstrip("\n")
        if not v.strip():
            return None
        return f"{pad}{v.strip()}"
    if n["k"] == "el":
        attrs = "".join(
            f" {k}" if v is True else f' {k}="{v}"'
            for k, v in n["attrs"].items()
        )
        if n["void"] or n["tag"].lower() in VOID:
            return f"{pad}<{n['tag']}{attrs}>"
        if not n["children"]:
            return f"{pad}<{n['tag']}{attrs}></{n['tag']}>"
        if (len(n["children"]) == 1 and n["children"][0]["k"] == "text"
                and "\n" not in n["children"][0]["value"]):
            return f"{pad}<{n['tag']}{attrs}>{n['children'][0]['value']}</{n['tag']}>"
        inner = "\n".join(ln for ln in _flatten_to_lines(n["children"], depth + 1))
        return f"{pad}<{n['tag']}{attrs}>\n{inner}\n{pad}</{n['tag']}>"
    return ""


def _html_lines(doc):
    return "\n".join(_flatten_to_lines(doc["children"])).split("\n")


def _line_builder(doc, lang):
    L = lambda s: _esc_dq(s)
    lines = _html_lines(doc)

    if lang == "c":
        body = "\n".join('  printf("' + L(ln) + '\\n");' for ln in lines)
        return ("#include <stdio.h>\n\n"
                "int main(void) {\n" + body + "\n  return 0;\n}\n")
    if lang == "bash":
        body = "\n".join("echo '" + ln.replace("'", "'\\''") + "'" for ln in lines)
        return "#!/usr/bin/env bash\n" + body + "\n"
    if lang == "powershell":
        body = "\n".join('Write-Output "' + L(ln) + '"' for ln in lines)
        return body + "\n"
    if lang == "perl":
        body = "\n".join('print "' + L(ln) + '\\n";' for ln in lines)
        return "#!/usr/bin/perl\nuse strict;\nuse warnings;\n\n" + body + "\n"
    if lang == "lua":
        body = "\n".join('print("' + L(ln) + '")' for ln in lines)
        return body + "\n"
    if lang == "r":
        body = "\n".join('cat("' + L(ln) + '\\n")' for ln in lines)
        return body + "\n"
    if lang == "matlab":
        body = "\n".join("disp('" + ln.replace("'", "''") + "')" for ln in lines)
        return body + "\n"
    if lang == "dart":
        body = "\n".join('  print("' + L(ln) + '");' for ln in lines)
        return "void main() {\n" + body + "\n}\n"
    if lang == "scala":
        body = "\n".join('  println("' + L(ln) + '")' for ln in lines)
        return "object Page extends App {\n" + body + "\n}\n"
    if lang == "groovy":
        body = "\n".join('println "' + L(ln) + '"' for ln in lines)
        return body + "\n"
    if lang == "julia":
        body = "\n".join('println("' + L(ln) + '")' for ln in lines)
        return body + "\n"
    if lang == "elixir":
        body = "\n".join('IO.puts("' + L(ln) + '")' for ln in lines)
        return body + "\n"
    if lang == "haskell":
        body = "\n".join('  putStrLn "' + L(ln) + '"' for ln in lines)
        return "main :: IO ()\nmain = do\n" + body + "\n"
    if lang == "fsharp":
        body = "\n".join('  printfn "' + L(ln) + '"' for ln in lines)
        return "[<EntryPoint>]\nlet main argv =\n" + body + "\n  0\n"
    if lang == "clojure":
        body = "\n".join('  (println "' + L(ln) + '")' for ln in lines)
        return "(defn -main []\n" + body + ")\n(-main)\n"
    if lang == "erlang":
        body = ",\n".join('    io:format("' + L(ln) + '~n")' for ln in lines)
        return "-module(page).\n-export([main/0]).\n\nmain() ->\n" + body + ".\n"
    if lang == "pascal":
        body = "\n".join("  writeln('" + ln.replace("'", "''") + "');" for ln in lines)
        return "program Page;\nbegin\n" + body + "\nend.\n"
    if lang == "vbnet":
        body = "\n".join('    Console.WriteLine("' + L(ln) + '")' for ln in lines)
        return "Module Page\n  Sub Main()\n" + body + "\n  End Sub\nEnd Module\n"
    if lang == "objc":
        body = "\n".join('    NSLog(@"' + L(ln) + '");' for ln in lines)
        return ("#import <Foundation/Foundation.h>\n\n"
                "int main() {\n@autoreleasepool {\n" + body + "\n}\nreturn 0;\n}\n")
    if lang == "sql":
        body = "\n".join("SELECT '" + ln.replace("'", "''") + "';" for ln in lines)
        return body + "\n"
    if lang == "css":
        return "/* CSS cannot represent HTML structure */\n"
    if lang == "jsx":
        body = "\n".join(lines)
        return ("import React from 'react';\n\n"
                "export default function Page() {\n"
                "  return (\n    <>\n" + _indent(body, "      ") + "\n    </>\n  );\n}\n")
    if lang == "vue":
        body = "\n".join(lines)
        return "<template>\n" + _indent(body, "  ") + "\n</template>\n"
    if lang == "swiftui":
        body = ",\n".join('      Text("' + L(ln) + '")' for ln in lines)
        return ("import SwiftUI\n\nstruct ContentView: View {\n  var body: some View {\n"
                "    VStack(alignment: .leading) {\n" + body + "\n    }\n  }\n}\n")
    body = "\n".join(lines)
    return "/* HTML output:\n" + body + "\n*/\n"


# =============================================================
#  Public dispatch
# =============================================================
_TIER1 = {
    "python":     html_to_python,
    "javascript": html_to_javascript,
    "typescript": html_to_typescript,
    "java":       html_to_java,
    "csharp":     html_to_csharp,
    "cpp":        html_to_cpp,
    "swift":      html_to_swift,
    "go":         html_to_go,
    "rust":       html_to_rust,
    "kotlin":     html_to_kotlin,
    "php":        html_to_php,
    "ruby":       html_to_ruby,
}


def emit_html(doc, target: str) -> str:
    if target == "html":
        return "\n".join(_flatten_to_lines(doc["children"])) + "\n"
    if target in _TIER1:
        return _TIER1[target](doc)
    return _line_builder(doc, target)
